# PokéClicker Español - Scripts Tampermonkey

.- Autor: Natch
---

## 📦 Contenido del paquete

1. **Questlines (questlines.json + script)**  
   - Funciona: Traduce todos los textos de misiones/questlines del juego.  
   - Líneas: 1872
   - Caracteres: 138.067  

2. **Localizaciones (locations.json + script)**  
   - Funciona: Traduce nombres de ciudades, rutas y mazmorras.  
   - Líneas: 486
   - Caracteres: 33.800 

3. **README.md** (este documento)

---

## ⚙️ Cómo funcionan los scripts

### 1️⃣ Questlines

- Diccionario `questTranslations` con todos los textos originales → traducciones.  
- Función principal: `traducirQuestlines()` recorre todos los elementos de quests en el DOM y reemplaza texto.  
- Persistencia:
  - **MutationObserver:** detecta cambios dinámicos del DOM (panel de quests que se recarga).  
  - **setInterval (1,5s):** asegura que cualquier cambio no detectado también se traduzca.  
- Consola registra cada quest traducida.  
- Resultado: todas las misiones aparecen en español, incluso si se generan dinámicamente.

### 2️⃣ Localizaciones

- Diccionario `traduccionesLugares` con todos los nombres de ciudades, rutas y mazmorras → traducciones.  
- Funciones clave:
  - `traducirTexto()` → reemplaza texto de cualquier nodo, priorizando coincidencias más largas.  
  - `traducirElemento()` → traduce nodos y atributos (`title`, `value`, `alt`, etc.).  
  - `traducirElementoKO()` → traduce textos generados por KnockoutJS.  
  - `traducirBotonesDinamicos()` → traduce botones y tooltips dentro de grupos dinámicos.  
- Persistencia:
  - **MutationObserver** → detecta elementos nuevos o cambios en el DOM.  
  - **setInterval (2s)** → asegura traducciones repetidas para elementos dinámicos.  
- Interceptores internos:
  - Reemplaza propiedades internas como `Game.player.town` y `Routes.getName()` para devolver siempre nombres traducidos.  
- Inicialización: traduce todos los elementos existentes al cargar el script.  
- Resultado: todos los nombres de ciudades, rutas y mazmorras aparecen en español en tiempo real, manteniendo compatibilidad con la lógica interna del juego.

---

## 📌 Uso

1. Instalar Tampermonkey en tu navegador.  
2. Crear un nuevo script y pegar el contenido de `questlines.js` o `locations.js`.  
3. Guardar y activar.  
4. Cargar PokéClicker y observar las traducciones en español.  

> Los scripts están diseñados para ejecutarse **sobre la versión web de PokéClicker** en tiempo real, sin modificar archivos del juego.

---

## ⚠️ Advertencias

- Traducciones **no oficiales**.
- No se garantiza compatibilidad futura con nuevas versiones del juego.  
- Evitar publicar o redistribuir sin permiso del equipo de PokéClicker.  
- Solo se recomienda para jugadores hispanohablantes que quieran disfrutar el juego traducido.

----------------------------------------------------------------------------------------------------------------------------------------

# PokéClicker Spanish - Tampermonkey Scripts

.- Author: Natch

## 📦 Package contents

1. **Questlines (questlines.json + script)**  
   - Function: Translates all quests text in the game.  
   - Lines: 1.872  
   - Characters: 138,067  

2. **Locations (locations.json + script)**  
   - Function: Translates names of towns, routes, and dungeons.  
   - Lines: 486
   - Characters: 33,800  

3. **README.md** (this document)

---

## ⚙️ How the scripts work

### 1️⃣ Questlines

- Dictionary `questTranslations` maps all original texts → translations.  
- Main function: `traducirQuestlines()` iterates over all quest DOM elements and replaces text.  
- Persistence:
  - **MutationObserver:** detects dynamic DOM changes (quest panel reloads).  
  - **setInterval (1.5s):** ensures any undetected changes are also translated.  
- Console logs each translated quest.  
- Result: All quests appear in Spanish, even if dynamically generated.

### 2️⃣ Locations

- Dictionary `traduccionesLugares` maps all towns, routes, and dungeons → translations.  
- Key functions:
  - `traducirTexto()` → replaces text of any node, prioritizing longer matches.  
  - `traducirElemento()` → translates nodes and attributes (`title`, `value`, `alt`, etc.).  
  - `traducirElementoKO()` → translates texts generated by KnockoutJS.  
  - `traducirBotonesDinamicos()` → translates buttons and tooltips in dynamic groups.  
- Persistence:
  - **MutationObserver:** detects new elements or DOM changes.  
  - **setInterval (2s):** ensures repeated translation for dynamic elements.  
- Internal interceptors:
  - Overrides internal properties like `Game.player.town` and `Routes.getName()` to always return translated names.  
- Initialization: translates all existing elements when script loads.  
- Result: All town, route, and dungeon names appear in Spanish in real time, keeping internal game logic intact.

---

## 📌 Usage

1. Install Tampermonkey in your browser.  
2. Create a new script and paste `questlines.js` or `locations.js`.  
3. Save and enable the script.  
4. Open PokéClicker and see translations in Spanish.  

> Scripts are designed to run **over the web version of PokéClicker** in real time, without modifying game files.

---

## ⚠️ Warnings

- **Unofficial translations**.
- Future compatibility with new versions of the game is not guaranteed.  
- Avoid publishing or redistributing without PokéClicker team permission.  
- Recommended only for Spanish-speaking players who want to enjoy the game translated.
