name: Release to GH Pages
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.RELEASE_BOT_ID }}
          private_key: ${{ secrets.RELEASE_BOT_PEM }}
          
      - name: Merge develop -> main
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ steps.generate_token.outputs.token }}
